In [1]:
import numpy as np
from scipy.optimize import fmin_bfgs

In [3]:
def f(x): # x is shape of (2,2)
    return np.sum(x**2)

In [6]:
init = np.array([[1,2],[3,4]])
xopt = fmin_bfgs(f, init, disp=True, callback=lambda x: print(x))

[0.81560007 1.63120014 2.44680022 3.26240029]
[0.40100432 0.80200798 1.2030123  1.60401662]
[-4.35522731e-07  5.28974349e-07  9.34516171e-08 -2.24815861e-07]
Optimization terminated successfully.
         Current function value: 0.000000
         Iterations: 3
         Function evaluations: 20
         Gradient evaluations: 4


In [5]:
xopt

array([-4.35522731e-07,  5.28974349e-07,  9.34516171e-08, -2.24815861e-07])

In [24]:
n = np.array([
    [1,2,3,4,5],
    [4,5,6,7,8],
    [7,8,9,10,11],
    [10,11,12,13,14]
])

In [45]:
print(n.shape)

(4, 5)


In [40]:

def split_array(arr, exclude_cols):
    # Splitting the array into columns that need optimization and those that don't
    need_opt = np.delete(arr, exclude_cols, axis=1)
    no_opt = arr[:, exclude_cols]
    return need_opt, no_opt


def merge_arrays(opt_arr, no_opt_arr, exclude_cols):
    # Initialize an array of the same shape as the original
    merged = np.empty((opt_arr.shape[0], opt_arr.shape[1] + no_opt_arr.shape[1]), dtype=opt_arr.dtype)

    # Insert the non-optimized columns at their original positions
    for col in exclude_cols:
        merged[:, col] = no_opt_arr[:, exclude_cols.index(col)]

    # Insert the optimized columns into the remaining positions
    opt_idx = 0
    for col in range(merged.shape[1]):
        if col not in exclude_cols:
            merged[:, col] = opt_arr[:, opt_idx]
            opt_idx += 1

    return merged


In [41]:
a, b = split_array(n, [1,2])

In [42]:
merge_arrays(a, b, [1,2])

array([[ 1,  2,  3,  4,  5],
       [ 4,  5,  6,  7,  8],
       [ 7,  8,  9, 10, 11],
       [10, 11, 12, 13, 14]])

In [44]:
b

array([[ 2,  3],
       [ 5,  6],
       [ 8,  9],
       [11, 12]])